try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

desc = 'A library for working with analysis files generated by the zinc scala compiler'
config = {
    'name': 'zincutils',
    'description': desc,
    'author': 'Pants Contributors',
    'url': 'https://pypi.python.org/pypi/zincutils',
    'author_email': 'pants-devel@groups.google.com',
    'version': '0.1',
    'install_requires': ['six'],
    'packages': ['zincutils'],
    'scripts': [],
}

setup(**config)
